apiVersion: v1
kind: Service
metadata:
  name: scaletest-service
  labels:
    app: scaletest-app
spec:
  selector:
    app: scaletest-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http-metrics
  type: ClusterIP